"""Optional pytest11 plugin: zero-config discovery of the admin smoke tests.

Loaded by pytest via the ``pytest11`` entry point when django-admin-tests
is installed. Never imported by ``django_admin_tests/testcases.py`` or the
``manage.py test`` path, so the core stays runner-agnostic.

Auto-collection is **opt-in**. Enable it in the host project's pytest
config::

    [tool.pytest.ini_options]
    django_admin_tests_auto = true

Off by default on purpose: installing a package should never silently add
tests that fail an existing CI run. Projects that enable it configure the
tests through Django settings (see ``django_admin_tests/settings.py``),
since there's no host-side Python to subclass.
"""

import warnings
from pathlib import Path

import pytest

AUTO_INI_NAME = "django_admin_tests_auto"
MARKER_NAME = "django_admin_tests"


def pytest_addoption(parser):
    parser.addini(
        AUTO_INI_NAME,
        help=(
            "Automatically collect django-admin-tests' AdminSmokeTestCase "
            "without importing it in your own test files."
        ),
        type="bool",
        default=False,
    )


def pytest_configure(config):
    # Registered here so consumers don't hit PytestUnknownMarkWarning for the
    # marker pytest-django derives from our django.test.tag(...).
    config.addinivalue_line(
        "markers",
        f"{MARKER_NAME}: admin smoke tests generated by django-admin-tests.",
    )


def pytest_collection_modifyitems(session, config, items):
    """Append the admin smoke tests when auto-collection is enabled.

    Collects the installed ``testcases`` module as a pytest ``Module`` so
    pytest's own unittest collector picks up ``AdminSmokeTestCase`` — no
    import needed in the host project's test files.
    """
    if not config.getini(AUTO_INI_NAME):
        return

    try:
        smoke_path = _smoke_module_path()
    except Exception as exc:  # pragma: no cover - defensive
        _warn_collection_failed(exc)
        return

    # Compare resolved paths, not nodeid prefixes: a host project with its
    # own top-level testcases.py would otherwise look like a match and
    # silently suppress injection.
    if any(getattr(item, "path", None) == smoke_path for item in items):
        return

    try:
        items.extend(_collect_smoke_items(session, smoke_path))
    except Exception as exc:
        # A misconfigured Django (or a broken admin import) shouldn't take
        # down collection of the host project's own tests.
        _warn_collection_failed(exc)


def _warn_collection_failed(exc):
    warnings.warn(
        f"django-admin-tests could not auto-collect its admin smoke tests: "
        f"{exc!r}. Set {AUTO_INI_NAME} = false to silence this.",
        stacklevel=2,
    )


def _smoke_module_path():
    from django_admin_tests import testcases

    return Path(testcases.__file__).resolve()


def _collect_smoke_items(session, smoke_path):
    module = pytest.Module.from_parent(session, path=smoke_path)
    return list(session.genitems(module))
